イベント参加規約のたたきを作成
FlutterKaigi/flutterkaigi pull request #4
Opened 2021-08-21 14:25 UTC by kikuchy

close https://github.com/FlutterKaigi/flutterkaigi/issues/3

規約っぽいものを作りました。
募集概要に掲載すれば良さそうな内容は省いており、権利関係などを明記するようにしています。
英語版は気力なくて作れていません…必要かなぁ…

2021-08-21 23:12 UTC, masashi-sutou requested changes

2021-08-21 23:12 UTC, masashi-sutou commented on Terms-for-Join.ja.md
> +1.FlutterKaigiは、本規約に承諾し第2条の参加申込を行った登壇希望者に対し、当イベントの参加を承諾する旨を適切な手段（電子メールなど）で通知するものとします。
```suggestion
1. FlutterKaigiは、本規約に承諾し第2条の参加申込を行った登壇希望者に対し、当イベントの参加を承諾する旨を適切な手段（電子メールなど）で通知するものとします。
```

2021-08-21 23:12 UTC, masashi-sutou commented on Terms-for-Join.ja.md
> +2. FlutterKaigiと登壇者間の当イベントの提供にかかる契約（以下「本契約」）は、登壇者の
- ここはまだ途中かな...

2021-08-21 23:12 UTC, masashi-sutou commented on Terms-for-Join.ja.md
> +3. 参加者は、当イベントの参加二歳にして、他の参加者から取得した一切の個人情報について、いかなる第三者にも開示または漏洩してはならないものとします。ただし、FlutterKaigiは、参加者による他の参加者の個人情報の取り扱いに関して一切の責任を追わないものとします。
```suggestion
3. 参加者は、当イベントの参加に際にして、他の参加者から取得した一切の個人情報について、いかなる第三者にも開示または漏洩してはならないものとします。ただし、FlutterKaigiは、参加者による他の参加者の個人情報の取り扱いに関して一切の責任を追わないものとします。
```

2021-08-21 23:28 UTC, jiyuujin reviewed
ひとまず日本語版できてから、英語版これからですかね

2021-08-21 23:28 UTC, jiyuujin commented on Terms-for-Join.ja.md
> +2. FlutterKaigiと登壇者間の当イベントの提供にかかる契約（以下「本契約」）は、登壇者の
文言が途中で切れている

2021-08-21 23:28 UTC, jiyuujin commented on Terms-for-Join.ja.md
> +3. 参加者は、当イベントの参加二歳にして、他の参加者から取得した一切の個人情報について、いかなる第三者にも開示または漏洩してはならないものとします。ただし、FlutterKaigiは、参加者による他の参加者の個人情報の取り扱いに関して一切の責任を追わないものとします。
`二歳に` を `に際` に修正

2021-08-21 23:28 UTC, jiyuujin commented on Terms-for-Join.ja.md
> +# 第2条（当イベントの申し込み）
第1条では h2 タグを利用しているが、第2条以降いずれも h1 タグを利用している
どちらかに統一した方が良さそう

2021-08-21 23:34 UTC, jiyuujin commented
英語版については基本的なベースに Google 翻訳を使えば良いのでは

2021-08-22 02:28 UTC, kikuchy commented on Terms-for-Join.ja.md
> +1.FlutterKaigiは、本規約に承諾し第2条の参加申込を行った登壇希望者に対し、当イベントの参加を承諾する旨を適切な手段（電子メールなど）で通知するものとします。
fixed 379bc2d

2021-08-22 02:28 UTC, kikuchy commented on Terms-for-Join.ja.md
> +3. 参加者は、当イベントの参加二歳にして、他の参加者から取得した一切の個人情報について、いかなる第三者にも開示または漏洩してはならないものとします。ただし、FlutterKaigiは、参加者による他の参加者の個人情報の取り扱いに関して一切の責任を追わないものとします。
fixed 379bc2d

2021-08-22 02:28 UTC, kikuchy commented on Terms-for-Join.ja.md
> +3. 参加者は、当イベントの参加二歳にして、他の参加者から取得した一切の個人情報について、いかなる第三者にも開示または漏洩してはならないものとします。ただし、FlutterKaigiは、参加者による他の参加者の個人情報の取り扱いに関して一切の責任を追わないものとします。
fixed 379bc2d

2021-08-22 02:28 UTC, kikuchy commented on Terms-for-Join.ja.md
> +# 第2条（当イベントの申し込み）
fixed 521c363

2021-08-22 02:29 UTC, kikuchy commented on Terms-for-Join.ja.md
> +2. FlutterKaigiと登壇者間の当イベントの提供にかかる契約（以下「本契約」）は、登壇者の
書き忘れてました…！ 
e36d22a で明記してみました

2021-08-22 02:29 UTC, kikuchy commented on Terms-for-Join.ja.md
> +2. FlutterKaigiと登壇者間の当イベントの提供にかかる契約（以下「本契約」）は、登壇者の
書き忘れでした…
e36d22a で書いてみました。どうでしょう？

2021-08-22 02:33 UTC, kikuchy commented
> 英語版については基本的なベースに Google 翻訳を使えば良いのでは

a800c79 とりあえず機械翻訳してリンクだけ直してみました。
英語の条文はどう書いたら良いのかわかってない上正確性を担保できる自信がないので、「日本語版が正である」という旨は書いておいたほうが良いですかね…

2021-08-22 02:44 UTC, jiyuujin commented on Terms-for-Join.ja.md
> +2. FlutterKaigiと登壇者間の当イベントの提供にかかる契約（以下「本契約」）は、登壇者の
@kikuchy Thanks, LGTM

2021-08-22 02:45 UTC, jiyuujin commented on Terms-for-Join.ja.md
> +3. 参加者は、当イベントの参加二歳にして、他の参加者から取得した一切の個人情報について、いかなる第三者にも開示または漏洩してはならないものとします。ただし、FlutterKaigiは、参加者による他の参加者の個人情報の取り扱いに関して一切の責任を追わないものとします。
@kikuchy Thanks, LGTM

2021-08-22 02:45 UTC, jiyuujin commented on Terms-for-Join.ja.md
> +# 第2条（当イベントの申し込み）
@kikuchy Thanks, LGTM

2021-08-22 02:56 UTC, jiyuujin commented on Terms-for-Join.md
> +1. This agreement stipulates the conditions applicable to participation in an event hosted by Flutter Kaigi (hereinafter referred to as "this event"). All participants of FlutterKaigi (hereinafter re
名称について `Flutter Kaigi` なのか `FlutterKaigi` なのか (スペースを開けるのか開けないのか)
個人的にはスペースを開けない方に揃えた方が良いと思う

いずれかのワードを全検索でかけてもらえれば修正も楽にできるかと

2021-08-22 07:18 UTC, mightyfrog commented on Terms-for-Join.ja.md
> +3. 参加者は、当イベントの参加に際して、他の参加者から取得した一切の個人情報について、いかなる第三者にも開示または漏洩してはならないものとします。ただし、FlutterKaigiは、参加者による他の参加者の個人情報の取り扱いに関して一切の責任を追わないものとします。
```suggestion
3. 参加者は、当イベントの参加に際して、他の参加者から取得した一切の個人情報について、いかなる第三者にも開示または漏洩してはならないものとします。ただし、FlutterKaigiは、参加者による他の参加者の個人情報の取り扱いに関して一切の責任を負わないものとします。
```

2021-08-22 07:18 UTC, mightyfrog commented on Terms-for-Join.md
> +1. This agreement stipulates the conditions applicable to participation in an event hosted by Flutter Kaigi (hereinafter referred to as "this event"). All participants of FlutterKaigi (hereinafter re
英語版は半端な翻訳だとリーガルな部分の担保ができないので今回は要らないと思う。

2021-08-22 12:54 UTC, kikuchy commented
> 英語版は半端な翻訳だとリーガルな部分の担保ができないので今回は要らないと思う。

同感です。責任取れない…
b5ed4bc で一旦消しました。

2021-08-22 23:52 UTC, jiyuujin commented on Terms-for-Join.md
> +1. This agreement stipulates the conditions applicable to participation in an event hosted by Flutter Kaigi (hereinafter referred to as "this event"). All participants of FlutterKaigi (hereinafter re
今回は英語版を作成しないので一旦クローズ

2021-08-23 00:54 UTC, jiyuujin approved these changes
LGTM

2021-08-23 04:24 UTC, merged